# Uncomment this line to define a global platform for your project
 platform :ios, '9.2'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'photoqn' do
  pod 'Alamofire'
  pod 'SwiftyJSON'
end

target 'photoqnTests' do

end

target 'photoqnUITests' do

end
